import { useEffect } from 'react'
import Head from 'next/head'
import { observer } from 'mobx-react-lite'
import { data } from '@/data'
import { api } from '@/api'
import { ProductData } from '@/api/interfaces'
import { store } from '@/store'
import { Main } from '@/components/layouts'
import { AdsTmp, CardProductTmp } from '@/components/templates'
import styles from '@/styles/home.module.scss'

interface HomeProps {
	productsData: ProductData[]
}

const Home: React.FC<HomeProps> = props => {
	const products = store.products.data

	useEffect(() => {
		store.cart.resolve()
		store.favorite.resolve()
		store.products.set(props.productsData)
	}, [])

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Main>
				<AdsTmp title="Всё для комфортной работы" data={data.ads} className={styles.ads} />

				{products?.map(item => (
					<CardProductTmp data={item} key={item.id} />
				))}
			</Main>
		</>
	)
}

export default observer(Home)

export const getServerSideProps = async () => {
	try {
		const productsData = await api.products.list()

		return {
			props: {
				productsData,
			},
		}
	} catch (err) {
		return { props: {} }
	}
}
