import Head from 'next/head'
import { observer } from 'mobx-react-lite'
import { Main } from '@/components/layouts'
import { AdsTmp } from '@/components/templates'
import { data } from '@/data'

const Home = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Main>
				<AdsTmp title="Всё для комфортной работы" data={data.ads} />
			</Main>
		</>
	)
}

export default observer(Home)
